### ISSUE TITLE
exe to write sector from command line

### ISSUE THREAD

**Issue by flexloop** [jschicht/SectorIo#1]
Hi-

There is a the disksector.exe program that lets you write to a specific sector but it does not work with Windows 7 64 bit.

Is it possible to write or obtain a command line version of sectorio that will allow me to write to specific sectors on a raw drive?

Thanks-

Flex

**Comment by jschicht** [comment]
That is possible, as it is exactly what SetMace does. You can look inside the SetMace code for that. There are limitations with doing this. Take a look at the readme of SetMace.
